"""Insula functional NMF (concat multi-phase discovery)."""

from src.nmf.waveform_analysis import (
    FUNCTION_COLORS,
    PHASE_WINDOWS,
    TASKS,
    discover_paths,
    fit_nmf_grid,
    held_out_contrasts,
    load_hga_rows,
    normalize_nmf_factors,
    orient_two_components,
    plot_spatial,
    plot_waveforms,
    phase_matrix,
    prepare_shape_matrix,
    restrict_windows,
    run,
    stimulus_matrix,
    summarize_held_out,
    within_subject_permutation_p,
    write_component_table,
)

__all__ = [
    "FUNCTION_COLORS",
    "PHASE_WINDOWS",
    "TASKS",
    "discover_paths",
    "fit_nmf_grid",
    "held_out_contrasts",
    "load_hga_rows",
    "normalize_nmf_factors",
    "orient_two_components",
    "plot_spatial",
    "plot_waveforms",
    "phase_matrix",
    "prepare_shape_matrix",
    "restrict_windows",
    "run",
    "stimulus_matrix",
    "summarize_held_out",
    "within_subject_permutation_p",
    "write_component_table",
]
